-- =================================================================
-- SQL Script for Mood Tracker LINE Bot
-- =================================================================
-- This script creates the necessary tables: `profiles` and `moods`.
-- You can run this entire script in the Supabase SQL Editor.
-- =================================================================


-- 1. Table for User Profiles
-- This table stores information about each unique LINE user.
-- The `id` column will store the LINE User ID.
-- -----------------------------------------------------------------
CREATE TABLE public.profiles (
  id TEXT NOT NULL,
  display_name TEXT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT profiles_pkey PRIMARY KEY (id)
);

COMMENT ON TABLE public.profiles IS 'Stores user profile information from LINE.';
COMMENT ON COLUMN public.profiles.id IS 'LINE User ID, serves as the primary key.';


-- 2. Table for Mood Entries
-- This table stores each mood log from users.
-- -----------------------------------------------------------------
CREATE TABLE public.moods (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  user_id TEXT NOT NULL,
  mood TEXT NOT NULL,
  note TEXT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT moods_pkey PRIMARY KEY (id),
  CONSTRAINT moods_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id) ON DELETE CASCADE
);

COMMENT ON TABLE public.moods IS 'Stores individual mood entries for each user.';
COMMENT ON COLUMN public.moods.user_id IS 'Foreign key referencing the user in the profiles table.';
COMMENT ON COLUMN public.moods.mood IS 'The mood recorded by the user (e.g., "Happy", "Sad").';
COMMENT ON COLUMN public.moods.note IS 'Optional text note associated with the mood entry.';


-- =================================================================
-- End of Script
-- Next Step: Enable Row Level Security (RLS) on both tables.
-- =================================================================
